## Import the Libraries

In [1]:
import numpy as np
import pandas as pd
#import matplotlib.pyplot as plt 
#import seaborn as sns

## Import the Dataset

In [2]:
cars_train = pd.read_csv(r'cars_train.csv', header=None)
cars_test = pd.read_csv(r'cars_test.csv', header=None)


###  Working on Train Data

In [3]:
print(cars_train.shape)
cars_train.head()


(1382, 7)


0      1      2     3      4    5      6
0  vhigh   high      3  more  small  low  unacc
1    low  vhigh      3     4  small  med  unacc
2    low   high  5more  more    big  low  unacc
3   high    med      4     2  small  med  unacc
4    low    low      3  more    big  med   good

In [4]:
print(cars_test.shape)
cars_test.head()

(346, 7)


0      1      2     3      4     5      6
0    med  vhigh  5more     4  small   low  unacc
1  vhigh   high      2     2    big   med  unacc
2    low   high      2  more  small   low  unacc
3  vhigh  vhigh      3     2    big  high  unacc
4    low    med      4     4    med   med   good

In [5]:
cars_train.columns=['buying','maint','doors','persons','lug_boot','safety','classes']
cars_test.columns=['buying','maint','doors','persons','lug_boot','safety','classes']


In [6]:
cars_train.head()

buying  maint  doors persons lug_boot safety classes
0  vhigh   high      3    more    small    low   unacc
1    low  vhigh      3       4    small    med   unacc
2    low   high  5more    more      big    low   unacc
3   high    med      4       2    small    med   unacc
4    low    low      3    more      big    med    good

In [7]:
cars_test.head()

buying  maint  doors persons lug_boot safety classes
0    med  vhigh  5more       4    small    low   unacc
1  vhigh   high      2       2      big    med   unacc
2    low   high      2    more    small    low   unacc
3  vhigh  vhigh      3       2      big   high   unacc
4    low    med      4       4      med    med    good

## Preprocessing 

### 1.Feature Selection: As Domian Knowledge all the columns are important

### 2.Handling Missing Values

In [8]:
cars_train.isna().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
classes     0
dtype: int64

In [9]:
cars_test.isna().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
classes     0
dtype: int64

In [10]:
cars_train.duplicated().sum()

0

In [11]:
# cars_test.drop('classes',axis=1,inplace=True) 2 tym run hogya
cars_test.head()

buying  maint  doors persons lug_boot safety classes
0    med  vhigh  5more       4    small    low   unacc
1  vhigh   high      2       2      big    med   unacc
2    low   high      2    more    small    low   unacc
3  vhigh  vhigh      3       2      big   high   unacc
4    low    med      4       4      med    med    good

### Converting Categorical Variables into Numerical Variables by using LabelEncoder()

In [12]:
colname = cars_train.columns
colname

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'classes'], dtype='object')

In [13]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

for x in colname:
    cars_train[x]=le.fit_transform(cars_train[x])

In [14]:
cars_train.head()
#acc==>0
#good==>1
#unacc==>2
#vgood==>3

buying  maint  doors  persons  lug_boot  safety  classes
0       3      0      1        2         2       1        2
1       1      3      1        1         2       2        2
2       1      0      3        2         0       1        2
3       0      2      2        0         2       2        2
4       1      1      1        2         0       2        1

In [15]:
colname = cars_test.columns
colname

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'classes'], dtype='object')

In [16]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

for x in colname:
    cars_test[x]=le.fit_transform(cars_test[x])

In [17]:
cars_test.head()

buying  maint  doors  persons  lug_boot  safety  classes
0       2      3      3        1         2       1        2
1       3      0      0        0         0       2        2
2       1      0      0        2         2       1        2
3       3      3      1        0         0       0        2
4       1      2      2        1         1       2        1

### Create X and Y

In [18]:
X = cars_train.values[:,0:-1]
Y = cars_train.values[:,-1]
Y=Y.astype(int)

In [19]:
print(X.shape)
print(Y.shape)

(1382, 6)
(1382,)


### In this case ideally scaling is not required because all the vairable have same number of category

In [20]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
scaler.fit(X)
X = scaler.transform(X)

In [21]:
print(X)

[[ 1.33507272 -1.3488262  -0.45682233  1.21505861  1.22565305  0.00176987]
 [-0.44760409  1.32688358 -0.45682233 -0.01064285  1.22565305  1.22474807]
 [-0.44760409 -1.3488262   1.33418038  1.21505861 -1.21505663  0.00176987]
 ...
 [-1.33894249  1.32688358  1.33418038 -0.01064285  0.00529821 -1.22120833]
 [ 0.44373431  0.43498032  0.43867903 -0.01064285 -1.21505663  0.00176987]
 [ 0.44373431 -0.45692294  1.33418038  1.21505861  1.22565305 -1.22120833]]


### Splitting the data into train and test

In [22]:
from sklearn.model_selection import train_test_split
 
#Split the data into test and train
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, 
                                                    random_state=10)

In [23]:
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(1105, 6)
(277, 6)
(1105,)
(277,)


## Running the Decision Tree Model

In [24]:
from sklearn.tree import DecisionTreeClassifier

# create a model object
model_DT = DecisionTreeClassifier(random_state=10,criterion='entropy')

#min_samples_leaf, min_samples_split, max_depth, max_features, max_leaf_nodes

# train the model object
model_DT.fit(X_train,Y_train)

Y_pred=model_DT.predict(X_test)
print(Y_pred)

[2 2 2 2 2 2 0 2 2 1 0 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 0 2 0 3 2 2 2 0 2
 2 0 2 2 2 2 2 3 0 2 0 3 0 2 0 2 2 2 2 2 2 0 2 0 2 2 0 2 2 0 2 0 0 2 2 0 3
 0 0 2 2 0 2 0 2 2 0 2 2 0 2 2 2 0 2 2 0 2 2 2 2 2 0 3 2 2 0 0 2 2 2 0 2 0
 3 2 0 3 2 2 2 2 2 3 2 0 2 0 2 2 0 2 2 2 2 0 2 2 2 2 0 2 2 2 0 2 2 2 0 0 2
 2 2 2 2 0 2 2 1 2 2 2 2 2 2 0 2 2 2 3 1 0 2 2 0 2 2 2 2 2 0 2 0 0 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 1 0 2 2 2 2 2 0 0 2 3 1 2 2 0 0 2 0 0
 0 2 2 0 2 2 2 2 0 0 0 2 2 2 0 2 0 2 0 0 0 1 1 2 2 2 0 2 2 2 2 0 1 2 2 2 2
 2 0 2 2 2 2 2 0 2 2 0 0 2 2 1 0 2 2]


In [25]:
print(list(zip(Y_test,Y_pred)))

[(2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (1, 1), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (0, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (0, 0), (1, 3), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (3, 3), (0, 0), (2, 2), (0, 0), (3, 3), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (1, 0), (2, 2), (0, 0), (0, 0), (2, 2), (2, 2), (0, 0), (3, 3), (0, 0), (0, 0), (2, 2), (2, 2), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (3, 3), (2, 2), (2, 2), (0, 0), (0, 0), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (0, 0), (3, 3), (2, 2), (0, 0), (3, 3), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (3, 3), (2, 2), (0, 0), (2, 2), (0, 0),

In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
print()
 
print("Classification report: ")

 
print(classification_report(Y_test,Y_pred))
print()

 
acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[ 69   1   1   0]
 [  3   8   0   1]
 [  0   0 185   0]
 [  0   0   0   9]]

Classification report: 
              precision    recall  f1-score   support

           0       0.96      0.97      0.97        71
           1       0.89      0.67      0.76        12
           2       0.99      1.00      1.00       185
           3       0.90      1.00      0.95         9

    accuracy                           0.98       277
   macro avg       0.94      0.91      0.92       277
weighted avg       0.98      0.98      0.98       277


Accuracy of the model:  0.9783393501805054


In [27]:
model_DT.score(X_train,Y_train)

1.0

### Even if the score function is giving us 100% accuracy it is not a case of overfitting. Given that our test data also shows a close by accuracy

In [28]:
model_DT.feature_importances_

array([0.20574531, 0.17463701, 0.06331063, 0.21101322, 0.10086451,
       0.24442932])

In [29]:
print((list(zip(cars_train.columns[0:-1],
               model_DT.feature_importances_))))

[('buying', 0.20574531001239776), ('maint', 0.17463701498971954), ('doors', 0.06331063297289136), ('persons', 0.21101322036210549), ('lug_boot', 0.10086450635635982), ('safety', 0.24442931530652598)]


In [30]:
sample=pd.DataFrame()
 
sample["Column"]=cars_train.columns[0:-1]
sample["Imp value"]=model_DT.feature_importances_
 
sample.sort_values("Imp value",ascending=False)


Column  Imp value
5    safety   0.244429
3   persons   0.211013
0    buying   0.205745
1     maint   0.174637
4  lug_boot   0.100865
2     doors   0.063311

### Note: If a Variable shows a exact zero value it means that the varibale was never used for spliting while building the tree. So we can eliminate such importance variable, we can also eliminate those Variables which show very low importance like 0.005. Assuming that this variable have been used very less number of time while.


In [31]:
from sklearn import tree
with open(r"model_DT.txt", "w") as f:
    
    f = tree.export_graphviz(model_DT, feature_names=cars_train.columns[0:-1],
                             out_file=f)
    
#generate the file and upload the code in webgraphviz.com to plot the decision tree

## Pruning

In [32]:
from sklearn.tree import DecisionTreeClassifier

# create a model object
model_DT = DecisionTreeClassifier(random_state=10,criterion='gini',
                                 splitter='best',
                                  min_samples_leaf=3,
                                 min_samples_split=5,
                                 max_depth=10)

#min_samples_leaf, min_samples_split, max_depth, max_features, max_leaf_nodes

# train the model object
model_DT.fit(X_train,Y_train)

Y_pred=model_DT.predict(X_test)
print(Y_pred)

[2 2 2 2 2 2 0 2 2 1 0 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 0 2 2 3 2 2 2 0 2
 2 0 2 2 2 2 2 3 0 2 0 3 0 2 0 2 2 2 2 2 2 0 2 2 2 2 0 2 2 1 2 0 0 2 2 0 3
 0 0 2 2 0 2 0 2 2 0 2 2 0 2 2 2 0 2 2 0 2 2 2 2 2 0 3 2 2 0 0 2 2 2 0 2 0
 3 2 0 3 2 2 2 2 2 3 2 0 2 0 2 2 0 2 2 2 2 0 2 2 2 2 0 2 2 2 0 2 2 2 0 0 0
 2 2 2 2 0 2 2 1 2 2 2 2 2 2 1 2 2 0 3 2 0 2 2 0 2 2 2 2 2 0 2 0 0 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 0 2 2 2 2 2 0 0 2 3 1 2 2 0 0 2 0 0
 0 2 2 0 2 2 2 2 0 0 0 2 2 2 0 2 0 2 1 0 0 0 1 2 2 2 0 2 2 2 2 2 1 2 2 2 2
 2 0 2 2 2 2 2 0 2 2 0 0 2 2 3 0 2 2]


In [33]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
print()
 
print("Classification report: ")

 
print(classification_report(Y_test,Y_pred))
print()

 
acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[ 66   0   5   0]
 [  1   8   1   2]
 [  2   0 183   0]
 [  0   0   0   9]]

Classification report: 
              precision    recall  f1-score   support

           0       0.96      0.93      0.94        71
           1       1.00      0.67      0.80        12
           2       0.97      0.99      0.98       185
           3       0.82      1.00      0.90         9

    accuracy                           0.96       277
   macro avg       0.94      0.90      0.91       277
weighted avg       0.96      0.96      0.96       277


Accuracy of the model:  0.9602888086642599


In [34]:
from sklearn.linear_model import LogisticRegression
# create a model object
logreg = LogisticRegression(multi_class='multinomial')
# train the model object
logreg.fit(X_train,Y_train)

Y_pred=logreg.predict(X_test)
print(Y_pred)

[2 2 2 2 2 0 2 2 2 0 0 2 0 2 2 2 2 2 0 2 2 2 2 0 2 2 2 2 3 0 2 2 2 0 2 2 2
 2 2 2 2 2 0 2 0 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 0 3
 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 0 2 2 2 2 2
 0 2 0 0 2 2 2 2 2 2 2 2 2 0 2 2 0 2 2 0 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 0 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 0 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 0 2 0 2 2 2 0 2 2 0 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 0 0 2 2 0 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 3 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2]


In [35]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
print()
 
print("Classification report: ")

 
print(classification_report(Y_test,Y_pred))
print()

 
acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[ 11   0  58   2]
 [  2   0  10   0]
 [ 18   0 167   0]
 [  6   0   2   1]]

Classification report: 
              precision    recall  f1-score   support

           0       0.30      0.15      0.20        71
           1       0.00      0.00      0.00        12
           2       0.70      0.90      0.79       185
           3       0.33      0.11      0.17         9

    accuracy                           0.65       277
   macro avg       0.33      0.29      0.29       277
weighted avg       0.56      0.65      0.59       277


Accuracy of the model:  0.6462093862815884


C:\Users\karim khan\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\karim khan\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\karim khan\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [36]:
np.set_printoptions(suppress=True)
Y_pred_prob=logreg.predict_proba(X_test)
Y_pred_prob

array([[0.17723996, 0.04469266, 0.77722473, 0.00084265],
       [0.07716139, 0.02202663, 0.90080527, 0.0000067 ],
       [0.14540796, 0.02338039, 0.83015498, 0.00105667],
       ...,
       [0.16631889, 0.04582859, 0.78778272, 0.0000698 ],
       [0.1018213 , 0.03768644, 0.86046754, 0.00002472],
       [0.05074201, 0.01342706, 0.93581987, 0.00001105]])

In [37]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
 
# first, initialize the classificators
tree= DecisionTreeClassifier(random_state=10) # using the random state for reproducibility
knn= KNeighborsClassifier(n_neighbors=5,metric='euclidean')
svm= SVC(kernel="rbf", gamma=0.1, C=1,random_state=10)
logreg=LogisticRegression(multi_class="multinomial",random_state=10)

In [38]:
# now, create a list with the objects 
models= [tree, knn, svm, logreg]

In [39]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
 
for model in models:
    model.fit(X_train, Y_train) # fit the model
    Y_pred= model.predict(X_test) # then predict on the test set
    accuracy= accuracy_score(Y_test, Y_pred) 
    clf_report= classification_report(Y_test, Y_pred) 
    print(confusion_matrix(Y_test,Y_pred))
    print("The accuracy of the ",type(model).__name__, " model is ", accuracy*100 )
    print("Classification report:\n", clf_report)
    print("\n")

[[ 69   1   1   0]
 [  4   8   0   0]
 [  0   0 185   0]
 [  0   0   0   9]]
The accuracy of the  DecisionTreeClassifier  model is  97.83393501805054
Classification report:
               precision    recall  f1-score   support

           0       0.95      0.97      0.96        71
           1       0.89      0.67      0.76        12
           2       0.99      1.00      1.00       185
           3       1.00      1.00      1.00         9

    accuracy                           0.98       277
   macro avg       0.96      0.91      0.93       277
weighted avg       0.98      0.98      0.98       277



[[ 65   1   5   0]
 [  8   4   0   0]
 [  1   0 184   0]
 [  2   0   1   6]]
The accuracy of the  KNeighborsClassifier  model is  93.50180505415162
Classification report:
               precision    recall  f1-score   support

           0       0.86      0.92      0.88        71
           1       0.80      0.33      0.47        12
           2       0.97      0.99      0.98       185


C:\Users\karim khan\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\karim khan\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\karim khan\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\karim khan\anaconda3\lib\site-p

In [40]:
from sklearn import svm
model_SVC=svm.SVC(kernel="rbf", gamma=0.1, C=90)
#fitting training data to the model
model_SVC.fit(X_train,Y_train)
 
Y_pred=model_SVC.predict(X_test)
#print(list(zip(Y_test,Y_pred)))

In [41]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
print()
 
print("Classification report: ")

 
print(classification_report(Y_test,Y_pred))
print()

 
acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[ 69   0   2   0]
 [  2  10   0   0]
 [  0   0 185   0]
 [  0   0   0   9]]

Classification report: 
              precision    recall  f1-score   support

           0       0.97      0.97      0.97        71
           1       1.00      0.83      0.91        12
           2       0.99      1.00      0.99       185
           3       1.00      1.00      1.00         9

    accuracy                           0.99       277
   macro avg       0.99      0.95      0.97       277
weighted avg       0.99      0.99      0.99       277


Accuracy of the model:  0.9855595667870036


### Out of the many model implemented Tuned SVM and Base DT work best for us. Out of the two we will finalize upon the base DT give us the almost the similar accuarcy and the complexity and the time consumption required by the Tuned SVM is more

### Working on Test Data

In [42]:
cars_test.head()

buying  maint  doors  persons  lug_boot  safety  classes
0       2      3      3        1         2       1        2
1       3      0      0        0         0       2        2
2       1      0      0        2         2       1        2
3       3      3      1        0         0       0        2
4       1      2      2        1         1       2        1

In [43]:
cars_test.drop(['classes'],axis=1,inplace=True)

In [44]:
test = cars_test.values
test = scaler.transform(test)

In [45]:
from sklearn.tree import DecisionTreeClassifier

# create a model object
model_DT = DecisionTreeClassifier(random_state=10)

#min_samples_leaf, min_samples_split, max_depth, max_features, max_leaf_nodes

# train the model object
model_DT.fit(X_train,Y_train)

DecisionTreeClassifier(random_state=10)

In [46]:
test_pred=model_DT.predict(test)
test_pred

array([2, 2, 2, 2, 1, 2, 0, 0, 2, 0, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 3,
       2, 0, 2, 2, 2, 2, 2, 0, 1, 3, 1, 2, 0, 2, 0, 2, 2, 2, 2, 3, 2, 2,
       0, 0, 2, 2, 3, 2, 2, 2, 1, 2, 0, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0,
       2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 1, 2, 2, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 0, 2, 2, 3, 2, 2, 0, 2, 0, 3, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2,
       2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 3, 2, 2,
       2, 2, 0, 0, 2, 2, 2, 2, 3, 2, 0, 2, 1, 0, 2, 2, 2, 2, 2, 3, 0, 0,
       2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 3, 0, 2, 2, 2, 3, 2, 2, 0, 2,
       2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 3, 2, 2, 0,
       2, 0, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 0, 2,
       2, 2, 0, 2, 2, 0, 2, 2, 2, 1, 1, 2, 2, 2, 0, 2, 2, 0, 3, 3, 0, 2,
       0, 2, 2, 2, 3, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2,

In [47]:
cars_test=pd.read_csv(r"cars_test.csv", header=None)
cars_test.columns=['buying','maint','doors','persons',
                   'lug_boot','safety','classes']
cars_test["Pred"]=test_pred
cars_test["Pred"]=cars_test["Pred"].replace({0:"acc",1:"good",2:"unacc",
                                         3:"vgood"})
cars_test.head()

buying  maint  doors persons lug_boot safety classes   Pred
0    med  vhigh  5more       4    small    low   unacc  unacc
1  vhigh   high      2       2      big    med   unacc  unacc
2    low   high      2    more    small    low   unacc  unacc
3  vhigh  vhigh      3       2      big   high   unacc  unacc
4    low    med      4       4      med    med    good   good

In [48]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(cars_test.classes,cars_test.Pred)
print(cfm)
print()
 
print("Classification report: ")

 
print(classification_report(cars_test.classes,cars_test.Pred))
print()

 
acc=accuracy_score(cars_test.classes,cars_test.Pred)
print("Accuracy of the model: ",acc)

[[ 60   1   3   0]
 [  3  10   0   0]
 [  0   0 251   0]
 [  0   0   0  18]]

Classification report: 
              precision    recall  f1-score   support

         acc       0.95      0.94      0.94        64
        good       0.91      0.77      0.83        13
       unacc       0.99      1.00      0.99       251
       vgood       1.00      1.00      1.00        18

    accuracy                           0.98       346
   macro avg       0.96      0.93      0.94       346
weighted avg       0.98      0.98      0.98       346


Accuracy of the model:  0.9797687861271677


### Saving a Excel file of the Test Output

In [49]:
cars_test.to_excel('Decision Test Output.xlsx',header=True)

In [50]:
import os
os.getcwd()

'C:\\Users\\karim khan\\Documents\\PGA 25\\Decision Tree'

## Conclusion:

### The Decision Tree Model gave us the Accuracy of 97.97% on the Test Data.

##  Bagging Techniques

In [51]:
#predicting using the Random_Forest_Classifier
from sklearn.ensemble import RandomForestClassifier
 
model_RandomForest=RandomForestClassifier(n_estimators=100,
                                          random_state=10, bootstrap=True,
                                         n_jobs=-1)
 
#fit the model on the data and predict the values
model_RandomForest.fit(X_train,Y_train)
 
Y_pred=model_RandomForest.predict(X_test)

In [53]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
print()
 
print("Classification report: ")

 
print(classification_report(Y_test,Y_pred))
print()

 
acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[ 65   1   5   0]
 [  4   8   0   0]
 [  1   0 184   0]
 [  0   0   0   9]]

Classification report: 
              precision    recall  f1-score   support

           0       0.93      0.92      0.92        71
           1       0.89      0.67      0.76        12
           2       0.97      0.99      0.98       185
           3       1.00      1.00      1.00         9

    accuracy                           0.96       277
   macro avg       0.95      0.89      0.92       277
weighted avg       0.96      0.96      0.96       277


Accuracy of the model:  0.9602888086642599


In [57]:
from sklearn.ensemble import ExtraTreesClassifier
 
model_EXT=ExtraTreesClassifier(n_estimators=100, random_state=10, bootstrap=True) #n_estimator will form no of trees according 
                                                                                  #to given value
#fit the model on the data and predict the values
model_EXT.fit(X_train,Y_train)
 
Y_pred=model_EXT.predict(X_test)

In [58]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
print()
 
print("Classification report: ")

 
print(classification_report(Y_test,Y_pred))
print()

 
acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[ 64   0   7   0]
 [  8   4   0   0]
 [  2   0 183   0]
 [  2   0   0   7]]

Classification report: 
              precision    recall  f1-score   support

           0       0.84      0.90      0.87        71
           1       1.00      0.33      0.50        12
           2       0.96      0.99      0.98       185
           3       1.00      0.78      0.88         9

    accuracy                           0.93       277
   macro avg       0.95      0.75      0.81       277
weighted avg       0.93      0.93      0.93       277


Accuracy of the model:  0.9314079422382672


In [62]:
from sklearn.ensemble import ExtraTreesClassifier
 
model_EXT=ExtraTreesClassifier( random_state=10, bootstrap=True)
 
parameter_space = {
    'n_estimators':[100,200,300,1000],    #np.arange(100, 1001,50)
    'max_depth':[10,15,8,12],
    'min_samples_leaf':[3,4,5,6,7]
    }
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(model_EXT, parameter_space, n_jobs=-1, cv=5)

In [63]:
clf.fit(X_train,Y_train)

GridSearchCV(cv=5,
             estimator=ExtraTreesClassifier(bootstrap=True, random_state=10),
             n_jobs=-1,
             param_grid={'max_depth': [10, 15, 8, 12],
                         'min_samples_leaf': [3, 4, 5, 6, 7],
                         'n_estimators': [100, 200, 300, 1000]})

In [64]:
print('Best parameters found:\n', clf.best_params_)

Best parameters found:
 {'max_depth': 15, 'min_samples_leaf': 3, 'n_estimators': 100}


In [65]:
clf.best_score_     #accuracy of the best params using the 5-fold CV

0.902262443438914

In [66]:
Y_pred=clf.predict(X_test)

In [67]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
print()
 
print("Classification report: ")

 
print(classification_report(Y_test,Y_pred))
print()

 
acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[ 57   0  14   0]
 [ 11   1   0   0]
 [  1   0 184   0]
 [  5   0   0   4]]

Classification report: 
              precision    recall  f1-score   support

           0       0.77      0.80      0.79        71
           1       1.00      0.08      0.15        12
           2       0.93      0.99      0.96       185
           3       1.00      0.44      0.62         9

    accuracy                           0.89       277
   macro avg       0.92      0.58      0.63       277
weighted avg       0.89      0.89      0.87       277


Accuracy of the model:  0.8880866425992779


In [68]:
from sklearn.ensemble import ExtraTreesClassifier
 
model_EXT=ExtraTreesClassifier( random_state=10, bootstrap=True)
 
parameter_space = {
    'n_estimators':np.arange(100, 1001,50)
    #'max_depth':[10,15,8,12],
    #'min_samples_leaf':[3,4,5,6,7]
    }
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(model_EXT, parameter_space, n_jobs=-1, cv=5)

In [69]:
clf.fit(X_train,Y_train)

GridSearchCV(cv=5,
             estimator=ExtraTreesClassifier(bootstrap=True, random_state=10),
             n_jobs=-1,
             param_grid={'n_estimators': array([ 100,  150,  200,  250,  300,  350,  400,  450,  500,  550,  600,
        650,  700,  750,  800,  850,  900,  950, 1000])})

In [70]:
print('Best parameters found:\n', clf.best_params_)

Best parameters found:
 {'n_estimators': 500}


In [71]:
clf.best_score_ 

0.9429864253393665

In [72]:
Y_pred=clf.predict(X_test)

In [73]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
print()
 
print("Classification report: ")

 
print(classification_report(Y_test,Y_pred))
print()

 
acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[ 63   0   8   0]
 [  8   4   0   0]
 [  1   0 184   0]
 [  2   0   0   7]]

Classification report: 
              precision    recall  f1-score   support

           0       0.85      0.89      0.87        71
           1       1.00      0.33      0.50        12
           2       0.96      0.99      0.98       185
           3       1.00      0.78      0.88         9

    accuracy                           0.93       277
   macro avg       0.95      0.75      0.81       277
weighted avg       0.93      0.93      0.92       277


Accuracy of the model:  0.9314079422382672


In [74]:
from sklearn.ensemble import ExtraTreesClassifier
 
model_EXT=ExtraTreesClassifier( random_state=10, bootstrap=True)
 
parameter_space = {
    'n_estimators':[100,200,300,1000],    #np.arange(100, 1001,50)
    'max_depth':[10,15,8,12],
    'min_samples_leaf':[3,4,5,6,7]
    }
from sklearn.model_selection import RandomizedSearchCV
clf = RandomizedSearchCV(model_EXT, parameter_space, n_jobs=-1, cv=5)

In [75]:
clf.fit(X_train,Y_train)

RandomizedSearchCV(cv=5,
                   estimator=ExtraTreesClassifier(bootstrap=True,
                                                  random_state=10),
                   n_jobs=-1,
                   param_distributions={'max_depth': [10, 15, 8, 12],
                                        'min_samples_leaf': [3, 4, 5, 6, 7],
                                        'n_estimators': [100, 200, 300, 1000]})

In [76]:
print('Best parameters found:\n', clf.best_params_)

Best parameters found:
 {'n_estimators': 100, 'min_samples_leaf': 3, 'max_depth': 8}


In [77]:
clf.best_score_ 

0.8895927601809955

In [78]:
Y_pred=clf.predict(X_test)

In [79]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
print()
 
print("Classification report: ")

 
print(classification_report(Y_test,Y_pred))
print()

 
acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[ 56   0  15   0]
 [ 11   1   0   0]
 [  1   0 184   0]
 [  6   0   0   3]]

Classification report: 
              precision    recall  f1-score   support

           0       0.76      0.79      0.77        71
           1       1.00      0.08      0.15        12
           2       0.92      0.99      0.96       185
           3       1.00      0.33      0.50         9

    accuracy                           0.88       277
   macro avg       0.92      0.55      0.60       277
weighted avg       0.89      0.88      0.86       277


Accuracy of the model:  0.8808664259927798
